# Generated by Django 3.1.7 on 2021-09-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210825_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='generated_deca',
            field=models.BooleanField(default=False),
        ),
    ]
